apiVersion: v1
kind: ConfigMap
metadata:
  name: profile-service-config
data:
  MONGO_URI: "{{ .Values.mongoURI }}"

[ec2-user@ip-10-0-0-32 templates]$ cat deployment-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: {{ .Values.image.frontend }}
          ports:
            - containerPort: 3000
