version: '3.8'

services:
  hello-service:
    build:
      context: ./helloService
      dockerfile: Dockerfile
    container_name: hello-service
    ports:
      - "3001:3001"  # Expose port 3001
    networks:
      - backend-network

  profile-service:
    build:
      context: ./profileService
      dockerfile: Dockerfile
    container_name: profile-service
    ports:
      - "3002:3002"  # Expose port 3002
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

